[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["ckie <git-525ff67@ckie.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
colored = "2.0.0"
